//! Keccak-256 counter-mode stream cipher.
//!
//! Binary-compatible with the Go Bee implementation in `pkg/encryption/`.

use alloy_primitives::Keccak256;

use super::KEY_SIZE;
use super::key::EncryptionKey;

/// Derive the keystream block for a given counter value.
///
/// Applies two rounds of Keccak-256:
///   round1 = Keccak256(key || LE32(counter))
///   round2 = Keccak256(round1)
#[inline]
fn derive_segment_key(key: &EncryptionKey, counter: u32) -> [u8; 32] {
    let mut hasher = Keccak256::new();
    hasher.update(<EncryptionKey as AsRef<[u8]>>::as_ref(key));
    hasher.update(counter.to_le_bytes());
    let ctr_hash = hasher.finalize();

    let mut hasher = Keccak256::new();
    hasher.update(ctr_hash.as_slice());
    hasher.finalize().into()
}

/// XOR `input` with the Keccak-256 CTR keystream, writing to `output`.
///
/// The keystream is generated by `derive_segment_key` for each 32-byte block,
/// starting at `init_ctr` and incrementing by 1 per block.
///
/// `output` must be at least as long as `input`. Bytes in `output` beyond
/// `input.len()` are left untouched.
#[inline]
pub fn transcrypt(key: &EncryptionKey, init_ctr: u32, input: &[u8], output: &mut [u8]) {
    debug_assert!(output.len() >= input.len());
    for (i, block) in input.chunks(KEY_SIZE).enumerate() {
        let segment_key = derive_segment_key(key, init_ctr.wrapping_add(i as u32));
        let start = i * KEY_SIZE;
        for (j, &byte) in block.iter().enumerate() {
            output[start + j] = byte ^ segment_key[j];
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test vector from Go: key=8abf1502..., 4096 zero bytes, init_ctr=0.
    /// Verifies binary compatibility with `bee/pkg/encryption/encryption_test.go`.
    #[test]
    fn go_test_vector() {
        let key_hex = "8abf1502f557f15026716030fb6384792583daf39608a3cd02ff2f47e9bc6e49";
        let key_bytes: [u8; 32] = hex::decode(key_hex).unwrap().try_into().unwrap();
        let key = EncryptionKey::from(key_bytes);

        let input = [0u8; 4096];
        let mut output = [0u8; 4096];
        transcrypt(&key, 0, &input, &mut output);

        let expected_hex = include_str!("testdata/go_vector_4096.hex");
        let expected = hex::decode(expected_hex.trim()).unwrap();
        assert_eq!(output.as_slice(), expected.as_slice());
    }

    #[test]
    fn symmetry() {
        let key = EncryptionKey::from([0x42; 32]);
        let plaintext = b"hello world, this is a test!!!!!"; // 32 bytes
        let mut ciphertext = [0u8; 32];
        let mut recovered = [0u8; 32];

        transcrypt(&key, 0, plaintext, &mut ciphertext);
        assert_ne!(&ciphertext[..], plaintext);

        transcrypt(&key, 0, &ciphertext, &mut recovered);
        assert_eq!(&recovered[..], plaintext);
    }

    #[test]
    fn segmented_equals_whole() {
        let key = EncryptionKey::from([0xaa; 32]);
        let input = [0x55u8; 128]; // 4 segments
        let mut whole = [0u8; 128];
        transcrypt(&key, 0, &input, &mut whole);

        // Encrypt each 32-byte segment separately with incrementing counter
        let mut segmented = [0u8; 128];
        for (i, chunk) in input.chunks(KEY_SIZE).enumerate() {
            transcrypt(&key, i as u32, chunk, &mut segmented[i * KEY_SIZE..]);
        }
        assert_eq!(whole, segmented);
    }

    #[test]
    fn partial_block() {
        let key = EncryptionKey::from([0x11; 32]);
        let input = [0xffu8; 17]; // Not aligned to 32 bytes
        let mut output = [0u8; 17];
        transcrypt(&key, 0, &input, &mut output);

        // Verify symmetry for partial block
        let mut recovered = [0u8; 17];
        transcrypt(&key, 0, &output, &mut recovered);
        assert_eq!(recovered, input);
    }

    #[test]
    fn nonzero_init_ctr() {
        let key = EncryptionKey::from([0x33; 32]);
        let input = [0u8; 32];
        let mut out_ctr0 = [0u8; 32];
        let mut out_ctr5 = [0u8; 32];

        transcrypt(&key, 0, &input, &mut out_ctr0);
        transcrypt(&key, 5, &input, &mut out_ctr5);

        // Different init_ctr must produce different keystream
        assert_ne!(out_ctr0, out_ctr5);
    }

    /// Hex encoding/decoding helper for test vectors (dev-dependency only).
    mod hex {
        pub(super) fn decode(s: &str) -> Result<Vec<u8>, String> {
            if !s.len().is_multiple_of(2) {
                return Err("odd length".into());
            }
            (0..s.len())
                .step_by(2)
                .map(|i| {
                    u8::from_str_radix(&s[i..i + 2], 16).map_err(|e| e.to_string())
                })
                .collect()
        }
    }
}
