//! Cross-member domain-separation fuzz of the chunk registry predicates.
//!
//! While the typeless wire path exists (bee-compat 1.x), trial-parse
//! disambiguation by address must stay sound: no byte string may certify
//! under two registry members for any address. A member certifies bytes only
//! at its self-derived address, so the obligation reduces to derived-address
//! distinctness whenever two members structurally parse the same bytes.
//! This obligation relaxes only when the legacy typeless wire ids are
//! retired downstream.
//!
//! Inputs are valid by construction, as in `chunk_roundtrip`: each exec
//! generates a chunk under one member and asserts its wire bytes never
//! certify under the other, then pins `StandardChunkSet::decode_wire` to the
//! generating member at the generated address.

#![no_main]

use alloy_primitives::{B256, b256};
use alloy_signer_local::PrivateKeySigner;
use arbitrary::{Arbitrary, Unstructured};
use libfuzzer_sys::fuzz_target;
use nectar_primitives::{
    ChunkOps, ChunkRegistry, ContentChunk, DEFAULT_BODY_SIZE, SingleOwnerChunk, StandardChunkSet,
    bytes::Bytes,
};

// The match below spells out the member cross-product by hand; a new
// registry member must extend it, so pin the cardinality.
const _: () = assert!(
    StandardChunkSet::MEMBERS.len() == 2,
    "extend the pair sweep for the new registry member"
);

/// Private key of the dispersed-replica owner, mirroring the constant in
/// `crates/primitives/src/chunk/single_owner.rs`.
const DISPERSED_REPLICA_OWNER_KEY: B256 =
    b256!("0x0100000000000000000000000000000000000000000000000000000000000000");

/// One structured input: a valid chunk under one registry member, so each
/// exec drives one direction of the member pair and the corpus covers both.
#[derive(Debug)]
enum ChunkInput {
    Content(ContentChunk<DEFAULT_BODY_SIZE>),
    SingleOwner(SingleOwnerChunk<DEFAULT_BODY_SIZE>),
}

impl<'a> Arbitrary<'a> for ChunkInput {
    fn arbitrary(u: &mut Unstructured<'a>) -> arbitrary::Result<Self> {
        if u.arbitrary()? {
            Ok(Self::Content(ContentChunk::arbitrary(u)?))
        } else {
            let key = B256::arbitrary(u)?;
            // Key of bee's dispersed-replica owner (`pkg/replicas`): SOCs it
            // signs face an extra id acceptance rule, so a random id does
            // not certify. Replica semantics are outside this pair sweep.
            if key == DISPERSED_REPLICA_OWNER_KEY {
                return Err(arbitrary::Error::IncorrectFormat);
            }
            let signer = PrivateKeySigner::from_bytes(&key)
                .map_err(|_| arbitrary::Error::IncorrectFormat)?;
            Ok(Self::SingleOwner(SingleOwnerChunk::arbitrary_signed(
                u, &signer,
            )?))
        }
    }
}

fuzz_target!(|input: ChunkInput| {
    match input {
        ChunkInput::Content(chunk) => {
            let address = *chunk.address();
            let wire: Bytes = chunk.into();

            // Own-member anchor: the generated bytes certify under CAC.
            let cac = ContentChunk::<DEFAULT_BODY_SIZE>::try_from(wire.as_ref())
                .expect("valid CAC wire bytes must parse as CAC");
            cac.verify(&address)
                .expect("valid CAC must certify at its own address");

            // Cross member: if the bytes also parse as a SOC, its derived
            // address must differ, so no address certifies both members.
            if let Ok(soc) = SingleOwnerChunk::<DEFAULT_BODY_SIZE>::try_from(wire.as_ref()) {
                assert_ne!(
                    soc.address(),
                    &address,
                    "CAC wire bytes derived the same address under SOC"
                );
                assert!(
                    soc.verify(&address).is_err(),
                    "CAC wire bytes certified under the SOC predicate"
                );
            }

            let decoded = StandardChunkSet::decode_wire(&address, wire)
                .expect("registry must decode a valid CAC at its address");
            assert!(
                decoded.is_content(),
                "registry disambiguated a CAC to another member"
            );
        }
        ChunkInput::SingleOwner(chunk) => {
            let address = *chunk.address();
            let wire: Bytes = chunk.into();

            // Own-member anchor: the generated bytes certify under SOC.
            let soc = SingleOwnerChunk::<DEFAULT_BODY_SIZE>::try_from(wire.as_ref())
                .expect("valid SOC wire bytes must parse as SOC");
            soc.verify(&address)
                .expect("valid SOC must certify at its own address");

            // Cross member: a SOC's bytes almost always parse as a CAC (a
            // span plus payload), so the derived address is the only guard.
            if let Ok(cac) = ContentChunk::<DEFAULT_BODY_SIZE>::try_from(wire.as_ref()) {
                assert_ne!(
                    cac.address(),
                    &address,
                    "SOC wire bytes derived the same address under CAC"
                );
                assert!(
                    cac.verify(&address).is_err(),
                    "SOC wire bytes certified under the CAC predicate"
                );
            }

            let decoded = StandardChunkSet::decode_wire(&address, wire)
                .expect("registry must decode a valid SOC at its address");
            assert!(
                decoded.is_single_owner(),
                "registry disambiguated a SOC to another member"
            );
        }
    }
});
